#
# production configuration
#
spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.148.106:3307/webdb?characterEncoding=utf8
      username: return0
      password: 1234
mybatis:
   config-location: classpath:mybatis/configuration.xml
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://49.247.9.194:8761/eureka
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            msa:
               service:
                  emaillist:
                     exception: ERROR
